### ISSUE TITLE
interpreter

### ISSUE THREAD

**Issue by Raiper34** [Shootervm/xtd_tests#2]
Neviem ale ako vy, ale ja musim vzdy menit interpreter z toho tvojho na ako smrcka povedal na skoro univerzalny #!/usr/bin/env bash

+task ma byt skor maly xtd
+cestu by som dal na PATH_TO_XTD="$PATH_TO_TESTS" aby stacilo vlozit subor do tohoto priecinku a spustit skript

**Comment by vmasek** [comment]
Solved (aspon myslim, skus)

**Comment by Raiper34** [comment]
done done :)
